#%Vocabulary 1.0
base: http://a.ml/vocabularies/test7#
vocabulary: test7
propertyTerms:
  any:
    range: any
  guid:
    range: guid
  float:
    range: float
  uri:
    range: uri
  string:
    range: string
  dateTime:
    range: dateTime
  double:
    range: double
  long:
    range: long
  boolean:
    range: boolean
  date:
    range: date
  integer:
    range: integer
  time:
    range: time