addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.3.1")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.13.2")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"            % "2.0.9")
addSbtPlugin("com.sonar-scala"    % "sbt-sonar"                % "2.3.0")
addSbtPlugin("net.virtual-void"   % "sbt-dependency-graph"     % "0.10.0-RC1")
addSbtPlugin("com.eed3si9n"       % "sbt-sriracha"             % "0.1.0")
addSbtPlugin("org.scala-js"       % "sbt-jsdependencies"       % "1.0.2")
