#%Dialect 1.0
dialect: example
version: 1.23a
nodeMappings:
  Anchor:
    classTerm: v3.Anchor
    mapping:
      value:
        propertyTerm: v3.value
        range: string
  Base:
    classTerm: v3.Base
    mapping:
      other:
        unique: true
        propertyTerm: v3.other
        range: bis.Other
  Simple:
    classTerm: v3.Simple
    mapping:
      s:
        propertyTerm: v3.s
        range: string
    extends: Base
documents:
  root:
    encodes: Simple
uses:
  bis: example23b.raml
external:
  v3: http://test.com/v3#
