#%Dialect 1.0
dialect: Test
nodeMappings:
  Local:
    classTerm: v3.Local
    mapping:
      a:
        propertyTerm: v3.a
        range: string
documents:
  root:
    encodes: Local
external:
  v3: http://test.com/v3#
